#! /bin/sh -e
### BEGIN INIT INFO
# Provides:          lhstat
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: System monitoring
# Description:       Debian init script for the lhstat system monitoring
### END INIT INFO
#
# Author:	Toni Prug <tony@irational.org>
#
set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin
NAME=lhstat
DAEMON=/usr/local/sbin/lhstat/lhstat.lisp
DETACHTTY=/usr/bin/detachtty
LOGDIR=/var/log
RUNDIR=/var/run
PIDFILE=$RUNDIR/$NAME.pid
DESC=" system monitoring"
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
    start)
	log_daemon_msg "Starting $DESC" $NAME
        start-stop-daemon --quiet --pidfile $PIDFILE --exec $DETACHTTY --start \
            -- --dribble-file $LOGDIR/$NAME.log \
            --log-file     $LOGDIR/detachtty.log \
            --pid-file     $PIDFILE \
            $RUNDIR/$NAME.socket \
	    $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping $DESC" $NAME
        start-stop-daemon --quiet --pidfile $PIDFILE --startas detachtty --signal 3 --stop
	log_end_msg $?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
